name: go-devcontainer
services:
  devcontainer:
    image: devcontainer-go:1.24.3
    build: .
    hostname: devcontainer
    working_dir: /usr/src/app
    environment:
      - TZ=Europe/Bucharest
      - GOPATH=/go
    volumes:
      - ..:/usr/src/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true
