name: go-devcontainer
services:
  devcontainer:
    image: devcontainer-go:1.24.3
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: vscode
        GO_VERSION: 1.24.3
    restart: unless-stopped
    user: vscode
    hostname: devcontainer
    working_dir: /usr/src/app
    volumes:
      - ..:/usr/src/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true
